Probar job create_and_merge_pr y conexion anltcs

diff --git a/.github/workflows/dbt_test_merge_wf.yml b/.github/workflows/dbt_test_merge_wf.yml
--- a/.github/workflows/dbt_test_merge_wf.yml
+++ b/.github/workflows/dbt_test_merge_wf.yml
@@ -50,7 +50,7 @@ jobs:
         id: run_tests
         working-directory: apps/dbt_app/          
         run: |
-          dbt debug -t rfnd > result.log || true
+          dbt debug -t anltcs > result.log || true
 
           if grep -q "All checks passed!" result.log; then
             echo "not_failures=true" >> "$GITHUB_OUTPUT"
@@ -81,32 +81,32 @@ jobs:
 
             ${{ steps.run_tests.outputs.test_output }}
 
-  # create_and_merge_pr:
-  #   name: Create and auto-merge PR to main if tests pass
-  #   needs: code_test
-  #   if: needs.code_test.outputs.not_failures == 'true'
-  #   runs-on: ubuntu-latest
-  #   env:
-  #     GH_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v3
-  #       with:
-  #         token: ${{ secrets.GH_PUSH_TOKEN }}
-  #         path: apps/dbt_app/
+  create_and_merge_pr:
+    name: Create and auto-merge PR to main if tests pass
+    needs: code_test
+    if: needs.code_test.outputs.not_failures == 'true'
+    runs-on: ubuntu-latest
+    env:
+      GH_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+        with:
+          token: ${{ secrets.GH_PUSH_TOKEN }}
+          path: apps/dbt_app/
   
-  #     - name: Create Pull Request
-  #       run: |
-  #         BRANCH=$(git rev-parse --abbrev-ref HEAD)
-  #         gh pr create --title "Auto PR" --body "Created by workflow" --base main --head "$BRANCH" || echo "PR may already exist"
+      - name: Create Pull Request
+        run: |
+          BRANCH=$(git rev-parse --abbrev-ref HEAD)
+          gh pr create --title "Auto PR" --body "Created by workflow" --base main --head "$BRANCH" || echo "PR may already exist"
   
-  #     - name: Get PR URL
-  #       id: pr
-  #       run: |
-  #         PR_URL=$(gh pr list --head "$(git rev-parse --abbrev-ref HEAD)" --json url -q '.[0].url')
-  #         echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"
+      - name: Get PR URL
+        id: pr
+        run: |
+          PR_URL=$(gh pr list --head "$(git rev-parse --abbrev-ref HEAD)" --json url -q '.[0].url')
+          echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"
   
-  #     - name: Enable auto-merge
-  #       if: steps.pr.outputs.pr_url != ''
-  #       run: |
-  #         gh pr merge "$PR_URL" --merge --auto || echo "Failed to enable auto-merge"
+      - name: Enable auto-merge
+        if: steps.pr.outputs.pr_url != ''
+        run: |
+          gh pr merge "$PR_URL" --merge --auto || echo "Failed to enable auto-merge"
