Update and rename pr-test-and-deploy.yml to pr_extract_app-test_and_deploy.yml

diff --git a/.github/workflows/pr_extract_app-test_and_deploy.yml b/.github/workflows/pr_extract_app-test_and_deploy.yml
--- a/.github/workflows/pr_extract_app-test_and_deploy.yml
+++ b/.github/workflows/pr_extract_app-test_and_deploy.yml
@@ -17,12 +17,12 @@ jobs:
           python-version: '3.10'
 
       - name: Install dependencies
-        run: pip install -r requirements.txt
+        run: pip install -r apps/extract_app/requirements.txt
 
       - name: Run tests
         id: run_tests
         run: |
-          pytest > result.log || echo "FAILED" > fail_flag
+          pytest apps/extract_app/tests/ > result.log || echo "FAILED" > fail_flag
 
       - name: Check test result
         id: check_result
